### ISSUE TITLE
pip install not working

### ISSUE THREAD

**Issue by jamestwebber** [iosonofabio/lshknn#1]
Looks like `pkgconfig` isn't in the requirements on PyPI.

**Comment by iosonofabio** [comment]
thanks for telling. It's in `requirements.txt` already, you think it's about the `install_requires` line in the `setup.py`? Anyway I pushed a new git commit with that fix, hopefully releasing again on pypi soon will fix.

**Comment by jamestwebber** [comment]
It may have been a matter of the version on PyPI being out of date. In the end I needed to install most of the requirements separately anyway, and it took some messing around with paths to get things to build (probably because of conda). Here is what ended up working (in a conda environment that had numpy already):

```sh
conda install pkgconfig
conda install cmake
conda install -c menpo eigen # required this channel to get the correct version
pip install pybind11
git clone https://github.com/iosonofabio/lshknn.git
cd lshknn
export CPLUS_INCLUDE_PATH=/Users/james.webber/anaconda3/envs/maca-dash/include/eigen3
python setup.py install
```

**Comment by iosonofabio** [comment]
soudns good. because it works on the CI server and we are not sure about your system, I'm closing this. thanks for reporting.

**Comment by jamestwebber** [comment]
It looks like it's just that one must install the requirements on manually, rather than building them into `setup.py` which is what I was expecting. For instance in `.travis_before_install.sh` you set up all of the dependencies before installing this repo.

A potential enhancement would be write a proper [build recipe for conda](https://conda.io/docs/user-guide/tasks/build-packages/recipe.html), so that all of these requirements could be installed in one line.

**Comment by iosonofabio** [comment]
Sure, I'm not very familiar with conda but feel free to to make a PR with the recipe continuously deploying to anaconda cloud or, if you prefer to maintain recipes by hand, add one to anaconda cloud.
